parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  strict: error
  semi: warn
  no-unused-vars:
  - warn
  no-undef: error
  react/prop-types: off
  react/display-name: off
extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  es6: true
  browser: true
  node: true
